HOST = "localhost"#"localhost"
PORT = 2_000
CLIENT_TIMEOUT = 10.0

DEFAULT_VEHICLE_MODEL = "vehicle.audi.tt"

DEFAULT_RGB_CAMERA_FOV = 110
DEFAULT_RGB_CAMERA_IM_WIDTH = 640
DEFAULT_RGB_CAMERA_IM_HEIGHT = 480
