from carla_utils.actors import RGBCamera, GreyScaleCamera

RGB_CAMERA_FOV = 110
RGB_CAMERA_IM_WIDTH = 84  # 160  # 640
RGB_CAMERA_IM_HEIGHT = 84  # 120  # 480
RGB_CAMERA_HISTORY = 4

IMG_DIMENSION = (
    RGB_CAMERA_IM_HEIGHT,
    RGB_CAMERA_IM_WIDTH,
    GreyScaleCamera.get_number_of_channels()
)

THROTTLE = [0.5]  # [0, 0.5, 1]
STEER = [-1, 0, 1]  # [-1, -0.5, 0, 0.5, 1]
BRAKE = [1]  # [0, 0.5, 1]

MINIMUM_SPEED_LIMIT_PERCENTAGE = 0.70
MAX_STOPPED_SECONDS_ALLOWED = 1  # 3
MAX_STEERING_SECONDS_ALLOWED = 7
END_EPISODE_AFTER_STOPPED_SECONDS = 3

MINIMUM_ANGLE_TO_SIDE_CHANGE = 140
NEXT_WAYPOINT_DISTANCE = 2.0

NUMBER_OF_VEHICLES = 0  # 21
NUMBER_OF_PEDESTRIANS = 0  # 5

PRINT_X_HEAP_VARIABLES = 20
PRINT_X_HEAP_VARIABLES_EVERY_Y_EPISODES = 1  # 1_000
