from models import *

INITIAL_EPSILON = 1  # initial value of epsilon
FINAL_EPSILON = 0.01  # final value of epsilon
EPSILON_DECAY = 0.95  # 0.9975 99975

EPISODES = 1000  # 100
SECONDS_PER_EPISODE = 40  # 10
AGGREGATE_STATS_EVERY_X_EPISODES = 50

MODEL_NAME = XceptionModel.get_model_name()

REPLAY_MEMORY_SIZE = 5_000
MIN_REPLAY_MEMORY_SIZE = 1_000
MINI_BATCH_SIZE = 16
PREDICTION_BATCH_SIZE = 1
TRAINING_BATCH_SIZE = MINI_BATCH_SIZE // 4
UPDATE_TARGET_EVERY = 5

DISCOUNT = 0.99
